import Head from "next/head";
import Image from "next/image";
import User from "../src/models/User";
import dbConnect from "../src/utils/dbConnect";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    await dbConnect();

    const users = await User.find({});
    console.log("users", users);

    return {
      props: {
        test: "hola",
      },
    };
  } catch (error) {
    console.log(error);
    return { props: { error: true } };
  }
}
